// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psiudycdmaaqrhwlbtwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzaXVkeWNkbWFhcXJod2xidHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNzEwMzEsImV4cCI6MjA2Mzg0NzAzMX0.2-11T8lQswE6k-PZgdQC6sHtmIMlilo9ABxLxk-Jajo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);